### ISSUE TITLE
Hoshinobot最近更新后载入模块出现错误

### ISSUE THREAD

**Issue by TinyTitanPro** [MiaoXia0/setuweb#3]
Hoshinobot在5.1期间的几次commit之后，setuweb模块载入时出现错误，查看日志后尝试将setuweb/bot.py第48-51行的try语句块以及第58-66行的if语句块注释并手动定义setu_url的值后恢复正常，猜测是ip = json.loads(requests.get('https://jsonip.com/').text)['ip']这句的缘故。

**Comment by MiaoXia0** [comment]
网络问题导致API调用出错 这个再启动一次应该就可以了
