### ISSUE TITLE
register_blueprint() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by renike** [MiaoXia0/setuweb#4]
最近新搭建bot，跑起来报这个，web端无法使用.
ERROR: Failed to import "hoshino.modules.setuweb.blueprint", error: register_blueprint() takes 2 positional arguments but 3 were given
  File "/data/pcrbot/HoshinoBot/hoshino/modules/setuweb/__init__.py", line 18, in <module>
    app.register_blueprint(bp, '/setu')  # 注册蓝图

**Comment by renike** [comment]
我试着把app.register_blueprint(bp, '/setu') 改成app.register_blueprint(bp,url_prefix='/setu')，web能访问，不过
lolicon的请求跳转到/setu/result，然后我看日志报了    quota = result['quota']
KeyError: 'quota'
lolicon的网站好像已经取消配额了，是因为这个无法匹配上？

**Comment by MiaoXia0** [comment]
注册蓝图使用最新版Hoishinobot不会有问题
第二个问题刚更新了使用新版v2api并可以使用tags和uids

**Comment by clacknya** [comment]
这个问题是由于 [aiocqhttp](https://github.com/nonebot/aiocqhttp) 的一次更新将 `Quart` 的依赖由 `Quart>=0.11,<0.12` 变更到 `Quart>=0.14,<0.15` ，导致 `register_blueprint` 的参数由原先的 (self, blueprint: Blueprint, url_prefix: Optional[str] = None, *, subdomain: Optional[str] = None,) 变为 (self, blueprint: Blueprint, *, url_prefix: Optional[str] = None, url_defaults: Dict[str, Any] = None, subdomain: Optional[str] = None, **options: Any,)，顺序失配。
使用最新版 `Hoishinobot` 照样存在问题，因为最新版的 `aiocqhttp` 的依赖是 `aiocqhttp~=1.4.0` ，所依赖的 `Quart` 正是 `Quart>=0.14,<0.15` 。
